background-processing/ExampleApp/config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"

  root to: "pages#homepage"

  get "/sales" => "sales#index", as: "sales_index"
  get "/sales/report" => "sales#report", as: "sales_report"

end

background-processing/ExampleApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

background-processing/ExampleApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

background-processing/ExampleApp/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def homepage
    render text: "HOMEPAGE"
  end

end

background-processing/ExampleApp/app/controllers/sales_controller.rb
class SalesController < ApplicationController

  def index
  end

  def report
    # generate_report()
    ReportWorker.perform_async("07-01-2016", "08-01-2016")
    render text: "REQUEST TO GENERATE A REPORT ADDED TO THE QUEUE"
  end

  private
  def generate_report
    sleep 30
  end

end

background-processing/ExampleApp/app/helpers/application_helper.rb
module ApplicationHelper
end

background-processing/ExampleApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

background-processing/ExampleApp/app/views/sales/index.html.erb
<style>

</style>

<div id="wrapper">

  <h1>Create A Sales Report</h1>

  <button class="generate-sales-report">
    GENERATE SALES REPORT
  </button>

  <div id="footer-javascripts">
    <script type="text/javascript">
      $("button.generate-sales-report").on("click", function() {
        window.location = "<%= sales_report_url %>"
      })
    </script>
  </div>

</div>

background-processing/ExampleApp/app/views/sales/report.html.erb
<style>
  .sales-report {
    height: 500px;
  }
</style>

<div id="wrapper">

  <h1>THIS IS THE SALES REPORT</h1>

  <%= image_tag "sales-report.png", class: "sales-report" %>

  <div id="footer-javascripts">
    <script type="text/javascript">
    </script>
  </div>

</div>